# This workflow will build the Java project in the physics-sim folder with Gradle and cache/restore dependencies.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: Physics Sim CI Build

on:
  push:
    paths:
      - 'physics-sim/**'
      - '.github/workflows/physics-sim-build.yml'

jobs:
  ci-build:
    runs-on: ubuntu-24.04

    env:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Execute Gradle build
      run: cd physics-sim && ./gradlew test

  spotless-check:
    runs-on: ubuntu-24.04

    env:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Check formatting with Spotless
      run: cd physics-sim && ./gradlew spotlessCheck
